# Generated by Django 5.2.7 on 2025-10-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('teacher_class', models.CharField(blank=True, max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
